### ISSUE TITLE
Works with Adventurer 4 (with modifications)

### ISSUE THREAD

**Issue by brendann993** [modrzew/hass-flashforge-adventurer-3#1]
Python is not my strong suit but I can confirm this appears to work with Adventurer 4 by adding a self.type == 'flashforge_adventurer_4' in the is_supported in sensor.py
Adventurer 3 and Adventurer 4 basically talk the same way so its to be expected

**Comment by modrzew** [comment]
Hey there! Thanks for the report 🙂 looks like Adventurer 3 and Adventurer 4 talk with outside world in the same manner. Happy to add a mention about that in the readme.

By the way, the dropdown for choosing the printer model doesn't really do much, other than letting the user know that this piece of code was only tested with that specific printer. It's likely it could work with other models (as in your case), but it's also likely it wouldn't (as highlighted in #2).

**Comment by terppatyyppi** [comment]
Can anyone please help me in making my Av. 4 compatible with this integration? 
The first message here explains it, but I'm unable to find any such place in sensor.py ("is.supported"), so I have no idea where to add the mentioned declaration.

**Comment by modrzew** [comment]
Hey @terppatyyppi, I've removed the printer type dropdown from the integration since my last comment, so you should be able to just install it and use it without having to adjust any code. Let me know how it goes.

**Comment by modrzew** [comment]
(I'll close this issue for now since there's nothing else to do for now.)

**Comment by terppatyyppi** [comment]
Thank you so much!

**Comment by roperstv** [comment]
This hacs worked straight out of the box for me using a Av. 4, entities/sub it seems to support are as follows 

- Camera
- Bed Temp
- Bed Desired Temp
- Nozzle Temp
- Nozzle Desired Temp
- Printing (Boolean)

**Progress** however results in reporting a 0, would be nice to be able to see the actual progress.

Thanks for building this mod. useful!

**Comment by Sereen666** [comment]
Adventurer 3 works out of the box.
Adventurer 4 took a bit of loading time but does work (however i changed the entity names to show that it is the Adventurer 4)

Many thanks for this integration tho!
Would be awsome if i could also manage the lights and such but this far verry happy!

Happy to test stuff if needed (i know a bit of programming), many thanks again!
