### ISSUE TITLE
Possible to get remaining print time?

### ISSUE THREAD

**Issue by DavidBoike** [modrzew/hass-flashforge-adventurer-3#10]
Is the remaining print time even available over the TCP interface?

I tried creating a datetime helper to capture the print start time, and then doing the math in template sensors using the percentage, but my numbers are wildly off what the front of the printer displays.

I'm guessing that the printer reports percentage as the percentage of layers that are complete. Well I happen to be printing basically an open-topped box at the moment, so of course the solid base is going to take much longer to print than the skinny walls. So right now the print is 3% done and while the printer says there is 6h 56m remaining, my templated sensors estimate 46.5 hours! Not very useful obviously.

But of course, if the TCP interface only exposes percentage as an integer, I'm guessing nothing can be done.

**Comment by modrzew** [comment]
I don't think it's available through the TCP interface. I based my code on https://github.com/Slugger2k/FlashForgePrinterApi which doesn't have any reference to remaining print time. Moreover, it's not displayed in the FlashPrint app, which would be the prime location to display it — leading me to think it's simply not there.

**Comment by DavidBoike** [comment]
Yeah, I kind of expected as much. Noticed the same thing that it's not shown in FlashPrint.

Thanks for the reply! Have really been enjoying being able to take a peek at the print in Home Assistant no matter where I am. Next I need to get another smart plug so if the print comes off the bed I can cut power remotely. :wink:
