### ISSUE TITLE
Dont see temperautre

### ISSUE THREAD

**Issue by askthomas** [modrzew/hass-flashforge-adventurer-3#3]
I don¨t se any temperatura on printer, 

![flashforge](https://user-images.githubusercontent.com/35760597/190895696-4da90591-68b5-4e17-a942-3ae800036ca4.png)

**Comment by modrzew** [comment]
Hey there @askthomas, it's hard to tell much from the screenshot you provided. Can you tell more about what you're trying to do, what you expect to see and what's happening?

**Comment by askthomas** [comment]
> Hey there @askthomas, it's hard to tell much from the screenshot you provided. Can you tell more about what you're trying to do, what you expect to see and what's happening?

Hi, On you sample picture yuo show 4 temperature values, 2 actual temperture and desired temperature, I dont get thoes entitese, I only get the 3 shown in my screenshoot.

**Comment by modrzew** [comment]
The nozzle and bed temperatures should be available as attributes on the `sensor.flashforge_adventurer_3_state` sensor. Some cards can access attributes — for example the `entities` card, though you need to use the code editor for that. If you want to have them as separate sensors, you should be able to create a separate [template sensor](https://www.home-assistant.io/integrations/template/) derived from their values. Hope that helps 🙂

**Comment by askthomas** [comment]
> The nozzle and bed temperatures should be available as attributes on the `sensor.flashforge_adventurer_3_state` sensor. Some cards can access attributes — for example the `entities` card, though you need to use the code editor for that. If you want to have them as separate sensors, you should be able to create a separate [template sensor](https://www.home-assistant.io/integrations/template/) derived from their values. Hope that helps 🙂

Aha, That I missed, yes the attributes was there. /Thanks
