### ISSUE TITLE
Temperature entity not working

### ISSUE THREAD

**Issue by Anyblade** [modrzew/hass-flashforge-adventurer-3#8]
Unable to read the temperature entity on the Flashforge Adventure 3 with newest firmware.

**Comment by modrzew** [comment]
Hey @Anyblade! I just checked on my printer and the temperature info seems to be correctly parsed during a print job.

![Screenshot 2023-03-02 at 22 52 13](https://user-images.githubusercontent.com/2963462/222421186-b00964ba-64cd-4dc4-8fed-ab1f965bbaf6.png)

Can you provide more details?

**Comment by modrzew** [comment]
@Anyblade I'm going to close this one, feel free to comment with more info.
