### ISSUE TITLE
Entities missing

### ISSUE THREAD

**Issue by Eiritj** [modrzew/hass-flashforge-adventurer-3#9]
Hi. Thanks a lot for making this.
I am only getting the camera feed, none of the other entities. 

![image](https://user-images.githubusercontent.com/118624769/221361545-ddd6e150-9d9c-4bf4-b9e9-6d624dc31a91.png)

Any clues to what I am doing wrong?

**Comment by modrzew** [comment]
Hey! Can you check your Home Assistant logs? There might be some hints as to what's wrong there.

**Comment by Eiritj** [comment]
Hi Modrzew, thank you for your reply. I recently updated HA and after the reset I got two more entities:

![image](https://user-images.githubusercontent.com/118624769/222886348-8606bebb-8eac-4373-b0ea-7e168206b87d.png)

In the logs I find the printer mentioned with this message:

Logger: homeassistant.components.sensor
Source: runner.py:179
Integration: Sensor (documentation, issues)
First occurred: March 3, 2023 at 8:35:01 AM (2 occurrences)
Last logged: March 3, 2023 at 8:35:01 AM

Setup of sensor platform flashforge_adventurer_3 is taking over 10 seconds.
Setup of sensor platform energy is taking over 10 seconds.

I am quite new with HA so I am not sure how to best provide relevant information to you. Any suggestions for how I should proceed would be greatly appreciated.

**Comment by modrzew** [comment]
Do those two entities work? Especially the state entity, it should indicate whether the printer is offline, online or printing.

**Comment by Eiritj** [comment]
Yes, they do work:
![image](https://user-images.githubusercontent.com/118624769/222964156-af3839f5-c83f-46c7-92b0-a8aae664e86b.png)

**Comment by modrzew** [comment]
Awesome! Looks like we can close this issue 😄
